// Null joint for the root-body
#include "joints/null/nullJoint.H"

// Composite joint to handle combination of rotations and translations
#include "joints/composite/compositeJoint.H"

// 6-DoF joint for floating bodies
#include "joints/floating/floatingJoint.H"

// Revolute joints
#include "joints/Rx/Rx.H"
#include "joints/Ry/Ry.H"
#include "joints/Rz/Rz.H"
#include "joints/Ra/Ra.H"
#include "joints/Rs/Rs.H"
#include "joints/Rzyx/Rzyx.H"
#include "joints/Rxyz/Rxyz.H"
#include "joints/Ryxz/Ryxz.H"

// Prismatic joints
#include "joints/Px/Px.H"
#include "joints/Py/Py.H"
#include "joints/Pz/Pz.H"
#include "joints/Pa/Pa.H"
#include "joints/Pxyz/Pxyz.H"
