/*---------------------------------------------------------------------------*\
Description
    Compatibility include.
    Previous support for forward declarations is no longer needed.

\*---------------------------------------------------------------------------*/

#ifndef HashFwd_H
#define HashFwd_H

#include "primitives/hashes/Hash/Hash.H"

#endif

// ************************************************************************* //
