/*---------------------------------------------------------------------------*\
Description
    Compatibility include

\*---------------------------------------------------------------------------*/

#ifndef FoamCompat_IStringStream_H
#define FoamCompat_IStringStream_H

#include "db/IOstreams/StringStreams/StringStream.H"

#endif

// ************************************************************************* //
