/*---------------------------------------------------------------------------*\
Description
    Compatibility include

\*---------------------------------------------------------------------------*/

#ifndef FoamCompat_OStringStream_H
#define FoamCompat_OStringStream_H

#include "db/IOstreams/StringStreams/StringStream.H"

#endif

// ************************************************************************* //
