/*---------------------------------------------------------------------------*\
Description
    Compatibility include

\*---------------------------------------------------------------------------*/

#ifndef Tstream_H
#define Tstream_H

#include "db/IOstreams/Tstreams/ITstream.H"
#include "db/IOstreams/Tstreams/OTstream.H"

#endif

// ************************************************************************* //
