/*---------------------------------------------------------------------------*\
Description
    Compatibility include

    foamVtkUIndPatchWriter.H combined into foamVtkIndPatchWriter.H (MAY-2022)

\*---------------------------------------------------------------------------*/

#ifndef Foam_vtk_UIndPatchWriter_H
#define Foam_vtk_UIndPatchWriter_H

#include "output/vtk/patch/foamVtkIndPatchWriter.H"

#endif

// ************************************************************************* //
